// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Meerkat Logging")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2016 Paul Hatcher")]
[assembly: AssemblyVersionAttribute("1.0.2")]
[assembly: AssemblyFileVersionAttribute("1.0.2")]
[assembly: AssemblyInformationalVersionAttribute("1.0.2 c5b1e5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Meerkat Logging";
        internal const System.String AssemblyCopyright = "Copyright © 2016 Paul Hatcher";
        internal const System.String AssemblyVersion = "1.0.2";
        internal const System.String AssemblyFileVersion = "1.0.2";
        internal const System.String AssemblyInformationalVersion = "1.0.2 c5b1e5";
    }
}
