// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Meerkat Logging")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2016 Paul Hatcher")]
[assembly: AssemblyVersionAttribute("2.3.0")]
[assembly: AssemblyFileVersionAttribute("2.3.0")]
[assembly: AssemblyInformationalVersionAttribute("2.3.0 11999f")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Meerkat Logging";
        internal const System.String AssemblyCopyright = "Copyright © 2016 Paul Hatcher";
        internal const System.String AssemblyVersion = "2.3.0";
        internal const System.String AssemblyFileVersion = "2.3.0";
        internal const System.String AssemblyInformationalVersion = "2.3.0 11999f";
    }
}
